# Generated by Django 2.2.16 on 2022-06-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220615_2002'),
        ('reviews', '0002_auto_20220613_1418'),
    ]

    operations = [
    ]
